services:
  # React Frontend
  - type: web
    name: ultrasound-frontend
    env: static
    buildCommand: cd ultrasound-dashboard && npm install && npm run build
    staticPublishPath: ultrasound-dashboard/build
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN

  # Flask Backend API
  - type: web
    name: ultrasound-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && gunicorn end_points:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9

  # Chainlit RAG Service
  - type: web
    name: ultrasound-chainlit
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd RAG && chainlit run chat_ultrasound_chroma.py -h --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9

  # Dash Feedback App
  - type: web
    name: ultrasound-feedback
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd RAG && python feedback_app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
